name: Deploy to CloudHub 2.0 via CLI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Anypoint CLI and CloudHub2 Plugin
        run: |
          npm install -g anypoint-cli-v4
          anypoint-cli-v4 plugins:install @mulesoft/cloudhub2


      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Login to Anypoint
        run: |
          anypoint-cli-v4 config set username $ANYPOINT_USERNAME
          anypoint-cli-v4 config set password $ANYPOINT_PASSWORD
          anypoint-cli-v4 config set organization "dd5302b1-b873-4250-b3ba-cff448dafdab"
          anypoint-cli-v4 config set environment "Sandbox"
          anypoint-cli-v4 login

      - name: Deploy to CloudHub 2.0
        run: |
          anypoint-cli-v4 runtime-mgr cloudhub2 deploy \
            --target cloudhub-us-east-2 \
            --name order-api \
            --file target/order-api.jar
