name: Build Mule App and Export JAR

on:
  push:
    branches:
      - master

env:
  ORG_ID: dd5302b1-b873-4250-b3ba-cff448dafdab
  ENV_ID: 869d18a5-39b8-4d21-8886-f2b8abea82c3
  DEPLOYMENT_TARGET_ID: 7e1948b7-68a0-4a5d-a561-95d620c41f7e
  APP_NAME: order-api
  VERSION: v1.0.0

jobs:
  build:
    name: Build JAR and Export Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Mule application
        run: |
          mvn clean package -DskipTests
          echo "✅ JAR built:"
          ls -lh target/*.jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-jar
          path: target/*.jar
